name: Action1
on:
  schedule:
    - cron: "0/5 * * * *"
  workflow_dispatch:

jobs:
  action:
    name: Action1
    runs-on: ubuntu-latest
    steps:
      - name: branch test 1
        run: |
          echo "Branch: ${{ github.ref_name }}"

      - name: branch test 2
        run: |
          echo "Branch: ${{ github.head_ref }}"

      - name: branch test 3
        run: |
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"

      - name: branch test 4
        run: |
          echo "Branch: ${{ github.event.repository.default_branch }}"

  call:
    name: Action1(call)
    uses: ./.github/workflows/action.yml
