name: Action
on:
  workflow_call:

jobs:
  action:
    name: Action
    runs-on: ubuntu-latest
    steps:
        - name: branch test 1
          run: |
            echo "Branch: ${{ github.ref_name }}"
  
        - name: branch test 2
          run: |
            echo "Branch: ${{ github.head_ref }}"
  
        - name: branch test 3
          run: |
            echo "Branch: ${{ github.event.workflow_run.head_branch }}"
  
        - name: branch test 4
          run: |
            echo "Branch: ${{ github.event.repository.default_branch }}"
